<a href="https://colab.research.google.com/github/imdoamaral/imersao_dados_python_alura/blob/main/imersao_dados_com_python_alura_agosto_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1 - Análise de Dados com Pandas

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

## Análise das variáveis numéricas

In [ ]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [ ]:
df.shape

(133349, 11)

In [ ]:
linhas, colunas = df.shape[0], df.shape[1]
print('linhas:', linhas)
print('colunas:', colunas)

linhas: 133349
colunas: 11

## Tradução das colunas para pt-BR via Gemini

In [ ]:
df.columns

Index(['ano_trabalho', 'nivel_experiencia', 'tipo_emprego', 'cargo', 'salario',
       'moeda_salario', 'salario_em_usd', 'residencia_empregado',
       'taxa_remoto', 'localizacao_empresa', 'tamanho_empresa'],
      dtype='object')

In [ ]:
# Create a dictionary for translating column names
translation_dict = {
    'ano_trabalho': 'ano',
    'nivel_experiencia': 'senioridade',
    'tipo_emprego': 'contrato',
    'cargo': 'cargo',
    'salario': 'salario',
    'moeda_salario': 'moeda',
    'salario_em_usd': 'usd',
    'residencia_empregado': 'residencia',
    'taxa_remoto': 'remoto',
    'localizacao_empresa': 'empresa',
    'tamanho_empresa': 'tamanho_empresa'
}

# Rename the columns using the dictionary
df.rename(columns=translation_dict, inplace=True)

# Display the translated columns
print("Colunas traduzidas:")
print(df.columns)

Colunas traduzidas:
Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

## Análise das variáveis categóricas

In [ ]:
df['senioridade'].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [ ]:
df['contrato'].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [ ]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [ ]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [ ]:
# Create a dictionary for translating 'senioridade' categories
senioridade_translation = {
    'SE': 'Senior',
    'MI': 'Médio',
    'EN': 'Iniciante',
    'EX': 'Executivo'
}

# Replace the values in the 'senioridade' column
df['senioridade'].replace(senioridade_translation, inplace=True)

# Display the updated value counts
print("Categorias da coluna 'senioridade' traduzidas:")
display(df['senioridade'].value_counts())

Categorias da coluna 'senioridade' traduzidas:

/tmp/ipython-input-2263402431.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['senioridade'].replace(senioridade_translation, inplace=True)

senioridade
Senior       77241
Médio        40465
Iniciante    12443
Executivo     3200
Name: count, dtype: int64

In [ ]:
# Create a dictionary for translating 'contrato' categories
contrato_translation = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelancer'
}

# Replace the values in the 'contrato' column
df['contrato'].replace(contrato_translation, inplace=True)

# Display the updated value counts
print("Categorias da coluna 'contrato' traduzidas:")
display(df['contrato'].value_counts())

Categorias da coluna 'contrato' traduzidas:

/tmp/ipython-input-2655716370.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['contrato'].replace(contrato_translation, inplace=True)

contrato
Tempo Integral    132563
Contrato             394
Tempo Parcial        376
Freelancer            16
Name: count, dtype: int64

In [ ]:
# Create a dictionary for translating 'tamanho_empresa' categories
tamanho_empresa_translation = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}

# Replace the values in the 'tamanho_empresa' column
df['tamanho_empresa'].replace(tamanho_empresa_translation, inplace=True)

# Display the updated value counts
print("Categorias da coluna 'tamanho_empresa' traduzidas:")
display(df['tamanho_empresa'].value_counts())

Categorias da coluna 'tamanho_empresa' traduzidas:

/tmp/ipython-input-1945066727.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tamanho_empresa'].replace(tamanho_empresa_translation, inplace=True)

tamanho_empresa
Médio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [ ]:
# Create a dictionary for translating 'remoto' categories
remoto_translation = {
    0: 'Presencial',
    100: 'Remoto',
    50: 'Híbrido'
}

# Replace the values in the 'remoto' column
df['remoto'].replace(remoto_translation, inplace=True)

# Display the updated value counts
print("Categorias da coluna 'remoto' traduzidas:")
display(df['remoto'].value_counts())

Categorias da coluna 'remoto' traduzidas:

/tmp/ipython-input-4036080148.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['remoto'].replace(remoto_translation, inplace=True)

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [ ]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Médio,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Médio,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Iniciante,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

## Análise categórica com describe()

In [ ]:
df.describe(include='object')

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Tempo Integral,Data Scientist,USD,US,Presencial,US,Médio
freq,77241,132563,17314,126140,119579,105312,119641,129561

## Análise numérica com describe()

In [ ]:
df.describe()

                 ano       salario            usd
count  133339.000000  1.333490e+05  133349.000000
mean     2024.358770  1.632833e+05  157617.272098
std         0.680627  2.173860e+05   74288.363097
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060200e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000

In [ ]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')

# Aula 2 - Preparação e Limpeza dos Dados

In [ ]:
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [ ]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [ ]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,Médio
59692,NaN,Médio,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,Médio
59710,NaN,Iniciante,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,Médio
59759,NaN,Senior,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,Médio
59789,NaN,Senior,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,Médio
131000,NaN,Senior,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,Médio
131006,NaN,Senior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Médio
133054,NaN,Iniciante,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Médio,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Médio,Tempo Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,Grande

In [ ]:
import numpy as np

# Criação de um dataframe de teste
df_salarios = pd.DataFrame({
    'nome': ['Israel', 'Matias', 'Amaral', 'Israelzinho', 'Israelzao'],
    'salario': [4000, np.nan, 5000, np.nan, 100000],
})

# Cria uma coluna de 'salario_media', substitui os nulos pela media e arredonda
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

# Cria uma coluna de 'salario_mediana' e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

          nome   salario  salario_media  salario_mediana
0       Israel    4000.0        4000.00           4000.0
1       Matias       NaN       36333.33           5000.0
2       Amaral    5000.0        5000.00           5000.0
3  Israelzinho       NaN       36333.33           5000.0
4    Israelzao  100000.0      100000.00         100000.0

In [ ]:
df_temperaturas = pd.DataFrame({
    'dia': ['segunda', 'terça', 'quarta', 'quinta', 'sexta'],
    'temperatura': [30, np.nan, np.nan, 28, 27]
})

# ffill = forward fill = preenche com o valor anterior
df_temperaturas['preenchido_ffill'] = df_temperaturas['temperatura'].ffill()

df_temperaturas

       dia  temperatura  preenchido_ffill
0  segunda         30.0              30.0
1    terça          NaN              30.0
2   quarta          NaN              30.0
3   quinta         28.0              28.0
4    sexta         27.0              27.0

In [ ]:
df_temperaturas = pd.DataFrame({
    'dia': ['segunda', 'terça', 'quarta', 'quinta', 'sexta'],
    'temperatura': [30, np.nan, np.nan, 28, 27]
})

# bfill = back fill = preenche com o valor posterior
df_temperaturas['preenchido_bfill'] = df_temperaturas['temperatura'].bfill()

df_temperaturas

       dia  temperatura  preenchido_bfill
0  segunda         30.0              30.0
1    terça          NaN              28.0
2   quarta          NaN              28.0
3   quinta         28.0              28.0
4    sexta         27.0              27.0

In [ ]:
df_cidades = pd.DataFrame({
    'nome': ['Israel', 'Matias', 'Amaral', 'Israelzinho', 'Israelzao'],
    'cidade': ['São Paulo', np.nan, 'Curitiba', np.nan, 'Belém']
})

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('Não informado')

df_cidades

          nome     cidade cidade_preenchida
0       Israel  São Paulo         São Paulo
1       Matias        NaN     Não informado
2       Amaral   Curitiba          Curitiba
3  Israelzinho        NaN     Não informado
4    Israelzao      Belém             Belém

In [ ]:
df_limpo = df.dropna()

In [ ]:
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [ ]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025,Médio,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025,Médio,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025,Iniciante,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [ ]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  int64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: int64(3), object(8)
memory usage: 12.2+ MB

In [ ]:
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))